=== Ldn26/xml/observations.dtd
<!ELEMENT observations (observation*)>
<!ELEMENT observation (id, YEAR, lieu, espece, NBR)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT lieu (id, nom, position)>
<!ELEMENT espece (nom, id, description)>
<!ELEMENT NBR (#PCDATA)>
<!ELEMENT position (X, Y)>
<!ELEMENT X (#PCDATA)>
<!ELEMENT Y (#PCDATA)>
<!ELEMENT YEAR   (#PCDATA)>
<!ELEMENT description   (#PCDATA)>

=== Ldn26/xml/oberservations-new.xml
<!DOCTYPE observations SYSTEM "observations.dtd">
<?xml version="1.0" encoding="UTF-8"?>
<observations>


<lieux  >
       <lieu id="blois" >
            <nom>Blois</nom>
            <position>
                <X>12</X>
                <Y>24</Y>
            </position>
        </lieu>

        <lieu id="tours" >
            <nom>Tours</nom>
            <position>
                <X>15</X>
                <Y>30</Y>
            </position>
        </lieu>
        <lieu id="orleans" >
            <nom>Orleans</nom>
            <position>
                <X>20</X>
                <Y>35</Y>
            </position>
        </lieu>
    </lieux>

        <especes >
        <espece id="rat" >
                    <nom>RAT</nom>
            <description>Petit animal </description>
        </espece>
        </especes  >




    <observation>
        <id>1</id>
        <YEAR>2024</YEAR>
        <lieu  ref="blois" />
      
        <espece  ref="rat" />
        <NBR>5</NBR>
    </observation>

    <observation>
        <id>2</id>
        <YEAR>2025</YEAR>
        <lieu  ref="tours" />
        <espece  ref="loup" />
        <NBR>3</NBR>
    </observation>

    <observation>
        <id>3</id>
        <YEAR>2023</YEAR>
        <lieu  ref="orleans" />
        <espece  ref="dauphin" />
        <NBR>8</NBR>
    </observation>

    <observation>
        <id>4</id>
        <YEAR>2022</YEAR>
        <lieu  ref="blois" />
        <espece  ref="dauphin" />
        <NBR>8</NBR>
    </observation>

    <observation>
        <id>4</id>
        <YEAR>2022</YEAR>
        <lieu  ref="blois" />
        <espece  ref="vache" />
        <NBR>6</NBR>
    </observation>

    <observation>
        <id>5</id>
        <YEAR>2024</YEAR>
        <lieu  ref="tours" />
        <espece  ref="vache" />
        <NBR>6</NBR>
    </observation>

    <observation>
        <id>5</id>
        <YEAR>2024</YEAR>
        <lieu  ref="orleans" />
        <espece  ref="vache" />
        <NBR>10</NBR>
    </observation>

    <observation>
        <id>6</id>
        <YEAR>2023</YEAR>
        <lieu  ref="orleans" />
        <espece  ref="vache" />
        <NBR>4</NBR>
    </observation>

    <observation>
        <id>7</id>
        <YEAR>2025</YEAR>
        <lieu  ref="orleans" />
        <espece  ref="vache" />
        <NBR>4</NBR>
    </observation>

    <observation>
        <id>7</id>
        <YEAR>2025</YEAR>
        <lieu  ref="orleans" />
        <espece>
            <nom>Oiseau</nom>
            <id>104</id>
            <description>Animal avec des plumes</description>
        </espece>
        <NBR>12</NBR>
    </observation>

    <observation>
        <id>8</id>
        <YEAR>2022</YEAR>
        <lieu  ref="tours" />
        <espece>
            <nom>lion</nom>
            <id>101</id>
            <description>grand animal </description>
        </espece>
        <NBR>7</NBR>
    </observation>

            </position>
        </lieu>
        <espece>
            <nom>lion</nom>
            <id>101</id>
            <description>grand animal </description>
        </espece>
        <NBR>7</NBR>
    </observation>

    <observation>
        <id>9</id>
        <YEAR>2025</YEAR>
        <lieu>
            <id>3</id>
            <nom>Orleans</nom>
            <position>
                <X>20</X>
                <Y>35</Y>
            </position>
        </lieu>
        <espece>
            <nom>cheval</nom>
            <id>103</id>
            <description>Animal </description>
        </espece>
        <NBR>9</NBR>
    </observation>

    <observation>
        <id>10</id>
        <YEAR>2024</YEAR>
        <lieu>
            <id>1</id>
            <nom>Blois</nom>
            <position>
                <X>12</X>
                <Y>24</Y>
            </position>
        </lieu>
        <espece>
            <nom>tigre</nom>
            <id>102</id>
            <description>Animal sauvage</description>
        </espece>
        <NBR>2</NBR>
    </observation>

    <observation>
        <id>11</id>
        <YEAR>2023</YEAR>
        <lieu>
            <id>2</id>
            <nom>Tours</nom>
            <position>
                <X>15</X>
                <Y>30</Y>
            </position>
        </lieu>
        <espece>
            <nom>Oiseau</nom>
            <id>104</id>
            <description>Animal avec des plumes</description>
        </espece>
        <NBR>15</NBR>
    </observation>

    <observation>
        <id>12</id>
        <YEAR>2025</YEAR>
        <lieu>
            <id>3</id>
            <nom>Orleans</nom>
            <position>
                <X>20</X>
                <Y>35</Y>
            </position>
        </lieu>
        <espece>
            <nom>renard</nom>
            <id>101</id>
            <description>Petit  </description>
        </espece>
        <NBR>11</NBR>
    </observation>

</observations>

=== Ldn26/xml/oberservations.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- calling dtd  -->
<!DOCTYPE observations SYSTEM "observations.dtd">
<observations>

    <observation>
        <id>1</id>
        <YEAR>2024</YEAR>
        <lieu>
            <id>1</id>
            <nom>Blois</nom>
            <position>
                <X>12</X>
                <Y>24</Y>
            </position>
        </lieu>
        <espece>
            <nom>RAT</nom>
            <id>101</id>
            <description>Petit animal </description>
        </espece>
        <NBR>5</NBR>
    </observation>

    <observation>
        <id>2</id>
        <YEAR>2025</YEAR>
        <lieu>
            <id>2</id>
            <nom>Tours</nom>
            <position>
                <X>15</X>
                <Y>30</Y>
            </position>
        </lieu>
        <espece>
            <nom>LOUP</nom>
            <id>102</id>
            <description>Animal sauvage</description>
        </espece>
        <NBR>3</NBR>
    </observation>

    <observation>
        <id>3</id>
        <YEAR>2023</YEAR>
        <lieu>
            <id>3</id>
            <nom>Orleans</nom>
            <position>
                <X>20</X>
                <Y>35</Y>
            </position>
        </lieu>
        <espece>
            <nom>dauphin</nom>
            <id>103</id>
            <description>Animal aquatique</description>
        </espece>
        <NBR>8</NBR>
    </observation>

    <observation>
        <id>4</id>
        <YEAR>2022</YEAR>
        <lieu>
            <id>1</id>
            <nom>Blois</nom>
            <position>
                <X>12</X>
                <Y>24</Y>
            </position>
        </lieu>
        <espece>
            <nom>vache</nom>
            <id>101</id>
            <description> animal  litier</description>
        </espece>
        <NBR>6</NBR>
    </observation>

    <observation>
        <id>5</id>
        <YEAR>2024</YEAR>
        <lieu>
            <id>2</id>
            <nom>Tours</nom>
            <position>
                <X>15</X>
                <Y>30</Y>
            </position>
        </lieu>
        <espece>
            <nom>chat</nom>
            <id>103</id>
            <description>Animal domestique</description>
        </espece>
        <NBR>10</NBR>
    </observation>

    <observation>
        <id>6</id>
        <YEAR>2023</YEAR>
        <lieu>
            <id>3</id>
            <nom>Orleans</nom>
            <position>
                <X>20</X>
                <Y>35</Y>
            </position>
        </lieu>
        <espece>
            <nom>chien</nom>
            <id>102</id>
            <description>  sauvage</description>
        </espece>
        <NBR>4</NBR>
    </observation>

    <observation>
        <id>7</id>
        <YEAR>2025</YEAR>
        <lieu>
            <id>1</id>
            <nom>Blois</nom>
            <position>
                <X>12</X>
                <Y>24</Y>
            </position>
        </lieu>
        <espece>
            <nom>Oiseau</nom>
            <id>104</id>
            <description>Animal avec des plumes</description>
        </espece>
        <NBR>12</NBR>
    </observation>

    <observation>
        <id>8</id>
        <YEAR>2022</YEAR>
        <lieu>
            <id>2</id>
            <nom>Tours</nom>
            <position>
                <X>15</X>
                <Y>30</Y>
            </position>
        </lieu>
        <espece>
            <nom>lion</nom>
            <id>101</id>
            <description>grand animal </description>
        </espece>
        <NBR>7</NBR>
    </observation>

    <observation>
        <id>9</id>
        <YEAR>2025</YEAR>
        <lieu>
            <id>3</id>
            <nom>Orleans</nom>
            <position>
                <X>20</X>
                <Y>35</Y>
            </position>
        </lieu>
        <espece>
            <nom>cheval</nom>
            <id>103</id>
            <description>Animal </description>
        </espece>
        <NBR>9</NBR>
    </observation>

    <observation>
        <id>10</id>
        <YEAR>2024</YEAR>
        <lieu>
            <id>1</id>
            <nom>Blois</nom>
            <position>
                <X>12</X>
                <Y>24</Y>
            </position>
        </lieu>
        <espece>
            <nom>tigre</nom>
            <id>102</id>
            <description>Animal sauvage</description>
        </espece>
        <NBR>2</NBR>
    </observation>

    <observation>
        <id>11</id>
        <YEAR>2023</YEAR>
        <lieu>
            <id>2</id>
            <nom>Tours</nom>
            <position>
                <X>15</X>
                <Y>30</Y>
            </position>
        </lieu>
        <espece>
            <nom>Oiseau</nom>
            <id>104</id>
            <description>Animal avec des plumes</description>
        </espece>
        <NBR>15</NBR>
    </observation>

    <observation>
        <id>12</id>
        <YEAR>2025</YEAR>
        <lieu>
            <id>3</id>
            <nom>Orleans</nom>
            <position>
                <X>20</X>
                <Y>35</Y>
            </position>
        </lieu>
        <espece>
            <nom>renard</nom>
            <id>101</id>
            <description>Petit  </description>
        </espece>
        <NBR>11</NBR>
    </observation>

</observations>
